### ISSUE TITLE
Using several prefixes at once

### ISSUE THREAD

**Issue by AlwxSin** [sobolevn/dump-env#11]
It will be useful if I can provide several prefixes. For example for one server I use specific pack of variables. And for another server I use the same pack, but replace one variable. 

For now I must use something like this
```bash
export SECRET_DOMAIN_NAME=another_domain.com
dump-env -p 'SECRET_' -t config/.env.template > config/.env
```
While I want something like this
```bash
dump-env -p 'SECRET_' -p 'DOMAIN_SPECIFIC' -t config/.env.template > config/.env
```

**Comment by sobolevn** [comment]
Added you as a collaborator
