### ISSUE TITLE
Move to poetry

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/dump-env#3]
We need to replace current `setup.py` solution with [`poetry`](https://github.com/sdispater/poetry).

Things to do:
1. remove `setup.py`
2. add `pyproject.toml`
3. resolve dependencies to create `pyproject.lock`

Here's an example of how it should be: https://github.com/wemake-services/wemake-python-styleguide

Here's how to use it: https://github.com/wemake-services/wemake-python-styleguide/blob/master/CONTRIBUTING.md

**Comment by tmsv** [comment]
@sobolevn Can you explain please where exactly should I replace setup.py to pyproject.toml?

**Comment by sobolevn** [comment]
The first step is to create `pyproject.toml`, then adding dev dependencies.

**Comment by tmsv** [comment]
> The first step is to create `pyproject.toml`, then adding dev dependencies.

Could you please tell me where should I get dev dependencies (I searched and read Google but didn't find intelligible answer). Thank you.

**Comment by sobolevn** [comment]
Closed via #6
