### ISSUE TITLE
Throw error if .env $VAR doesn't exists on environment

### ISSUE THREAD

**Issue by murilo-campaner** [sobolevn/dump-env#9]
Hello!

First of all, thanks for this amazing lib.

It's too much hard to develop a feature that we can pass an option like `--var-not-found=error` to throw error when one variable exists on env-template but doesn't exists on environment?

I think this is a good feature to remember development team that they need add that var in CI tool and  not only in .env/.env.template, thus it don't will pass on CI validation.

Thank you!

**Comment by sobolevn** [comment]
Hm, yes, I can see a usecase for it.

How about `--strict=ONE,TWO,THREE`?
This feature should not too hard and I would be happy if you contribute it.

Plan:
1. Add new flag to CLI
2. When fetching all env var - we can run validation and fail if any vars from the list are missing
3. Show message to the user

**Comment by sobolevn** [comment]
Hey, @AlwxSin! Can we please include this feature into the upcoming release?

**Comment by AlwxSin** [comment]
@sobolevn @murilo-campaner How about
```bash
# if even one variable from template does not exists in os environment throw an error
dump-env -t template.env --strict 

# if one of ONE,TWO,THREE variables from template does not exists in os environment throw an error
dump-env -t template.env --strict=ONE,TWO,THREE

# throw an error because there is no template given for strict option
dump-env --strict
```

**Comment by sobolevn** [comment]
@AlwxSin 👍

**Comment by AlwxSin** [comment]
@sobolevn yeah, make sense `dump-env --strict=ONE,TWO` should throw an error if ONE,TWO does not exists.
Will do that.
